// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzGuPhS5Mqx4cP1_Ey72iyE6DTHipC8IM',
    appId: '1:535701386896:web:1a8afc4b6f93305895ca15',
    messagingSenderId: '535701386896',
    projectId: 'horse-racing-bb0ef',
    authDomain: 'horse-racing-bb0ef.firebaseapp.com',
    storageBucket: 'horse-racing-bb0ef.firebasestorage.app',
    measurementId: 'G-D1ZN59LLJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYI2XUL9-kUkKOjJ74hHrHIOd77AMy1oc',
    appId: '1:535701386896:android:9ac50f604bf33db695ca15',
    messagingSenderId: '535701386896',
    projectId: 'horse-racing-bb0ef',
    storageBucket: 'horse-racing-bb0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGGmUVI9RYNp_ralG0869ayDvQGcrRq0',
    appId: '1:535701386896:ios:e0281904df75588c95ca15',
    messagingSenderId: '535701386896',
    projectId: 'horse-racing-bb0ef',
    storageBucket: 'horse-racing-bb0ef.firebasestorage.app',
    iosBundleId: 'com.example.horseRacing',
  );
}
